/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package com.mycompany.proyecto2_agenciafiscal;

import INegocios.ILicenciaNegocios;
import com.mycompany.proyecto2_agenciafiscalDTO.LicenciaNuevaDTO;
import com.mycompany.proyecto2_agenciafiscaldominio.Clientes;
import com.mycompany.proyecto2_agenciafiscaldominio.Licencia;
import com.mycompany.proyecto2_agencianegocio.LicenciaNegocio;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Oley
 */
public class Licencia01 extends javax.swing.JPanel implements java.beans.Customizer {

    private Clientes cliente;
    private ILicenciaNegocios LicenciaNegocio;
    private int anio = 0;
    private Object bean;

    /**
     * Creates new customizer Licencia
     */
public Licencia01(Clientes cliente, ILicenciaNegocios LicenciaNegocio) {
    this.cliente = cliente;
    this.LicenciaNegocio = LicenciaNegocio;
    initComponents();
}


    public void setObject(Object bean) {
        this.bean = bean;
        
    }

 public void precios() {
    if (Año.getSelectedItem().equals("1 año")) {
        if (cliente.isDiscapacitado()) { // Si el cliente está discapacitado
            txtcosto.setText("200");
        } else {
            txtcosto.setText("600");
        }
        anio = 1;
    } else if (Año.getSelectedItem().equals("2 año")) {
        if (cliente.isDiscapacitado()) { // Si el cliente está discapacitado
            txtcosto.setText("500");
        } else {
            txtcosto.setText("900");
        }
        anio = 2;
    } else if (Año.getSelectedItem().equals("3 año")) {
        if (cliente.isDiscapacitado()) { // Si el cliente está discapacitado
            txtcosto.setText("700");
        } else {
            txtcosto.setText("1100");
        }
        anio = 3;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Año = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtcosto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Vigencia");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        Año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 año", "2 año", "3 año" }));
        Año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñoActionPerformed(evt);
            }
        });
        add(Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel2.setText("Costo:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        txtcosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcostoActionPerformed(evt);
            }
        });
        add(txtcosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 100, -1));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 100, -1));

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñoActionPerformed
        precios();
    }//GEN-LAST:event_AñoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

 SolicitarLicencia01 formInicio = new SolicitarLicencia01();
        formInicio.setVisible(true);
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose(); 




    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  agregar();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostoActionPerformed


public void agregar() {
   if (cliente != null && cliente.getNombreCompleto() != null && !cliente.getNombreCompleto().isEmpty()) {
        String nombreSolicitante = cliente.getNombreCompleto();
        if (nombreSolicitante != null) {
            // Obtener el costo de la licencia
            float costo = Float.parseFloat(txtcosto.getText());
            
            // Obtener la vigencia seleccionada
            String selectedItem = (String) Año.getSelectedItem();
            int vigencia = 0;

            if (selectedItem != null && selectedItem.contains(" ")) {
                vigencia = Integer.parseInt(selectedItem.split(" ")[0]);
            } else {
                // Manejar el caso cuando no se puede obtener la vigencia correctamente
                JOptionPane.showMessageDialog(this, "Error al obtener la vigencia.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Salir del método si no se puede obtener la vigencia correctamente
            }
            
            // Crear un objeto Calendar para la fecha actual
            Calendar calendario = Calendar.getInstance();
            
            // Obtener el año actual y sumarle la vigencia seleccionada
            int ano = calendario.get(Calendar.YEAR) + vigencia;
            
            // Crear un nuevo objeto Calendar con la fecha de vencimiento calculada
            Calendar cal = new GregorianCalendar(ano, calendario.get(Calendar.MONTH), calendario.get(Calendar.DAY_OF_MONTH));
            
            // Crear un objeto LicenciaNuevaDTO con los datos proporcionados
            LicenciaNuevaDTO licenciaNuevaDTO = new LicenciaNuevaDTO(cal, cal, "Vigencia", costo);
            
            // Llamar al método agregarLicencia de LicenciaNegocio para guardar la licencia
            Licencia licenciaGuardada = LicenciaNegocio.agregarLicencia(licenciaNuevaDTO);
            
            // Verificar si la licencia se guardó correctamente
            if (licenciaGuardada != null) {
                JOptionPane.showMessageDialog(this, "Se completó el trámite de licencia a nombre de: " + nombreSolicitante);
            } else {
                JOptionPane.showMessageDialog(this, "Hubo un error al intentar completar su trámite", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El nombre del solicitante es nulo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Cliente no encontrado o nombre vacío.", "Error", JOptionPane.ERROR_MESSAGE);
    }
   
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Año;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtcosto;
    // End of variables declaration//GEN-END:variables
}
