/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package com.mycompany.proyecto2_agenciafiscal;

import INegocios.ILicenciaNegocios;
import com.mycompany.proyecto2_agenciafiscaldominio.Clientes;
import com.mycompany.proyecto2_agencianegocio.LicenciaNegocio;
import com.mycompany.proyecto2_agenciapersistencias.ClientesDAO;
import com.mycompany.proyecto2_agenciapersistencias.ConexionBase;
import com.mycompany.proyecto2_agenciapersistencias.IClientesDAO;
import com.mycompany.proyecto2_agenciapersistencias.IConexion;
import com.mycompany.proyecto2_agenciapersistencias.ILicenciaDAO;
import com.mycompany.proyecto2_agenciapersistencias.LicenciaDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Calendar;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.Query;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oley
 */
public class SolicitarPlaca extends javax.swing.JPanel implements java.beans.Customizer {

    private Object bean;
    private int selectedRow = -1;
private ILicenciaDAO licenciaDAO;
    /**
     * Creates new customizer SolicitarLicencia01
     */
    public SolicitarPlaca() {
          initComponents();

    }

    public void setObject(Object bean) {
        this.bean = bean;
    }

private Clientes Checar(String rfc) {
    System.out.println("Buscando cliente con RFC: " + rfc); 

    ConexionBase conexionBD = new ConexionBase();
    EntityManager entity = conexionBD.crearConexion();
    Query query = entity.createNativeQuery("SELECT * FROM Clientes WHERE rfc = ?", Clientes.class);
    query.setParameter(1, rfc);

    Clientes cli = null;
    try {
        cli = (Clientes) query.getSingleResult();
    } catch (NoResultException e) {
        cli = null;
    }

    if (cli != null) {
        System.out.println("Cliente encontrado: " + cli.toString());
    } else {
        System.out.println("Cliente no encontrado.");
    }

    return cli;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLicencia = new javax.swing.JTable();
        btnContinuar = new javax.swing.JButton();
        btnnRegresar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("RFC:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 250, 30));

        tblLicencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Fecha de nacimiento", "Discapacitado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLicencia);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 540, 160));

        btnContinuar.setText("Continuar");
        btnContinuar.setEnabled(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        btnnRegresar.setText("Regresar");
        btnnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnRegresarActionPerformed(evt);
            }
        });
        add(btnnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String rfc = jTextField1.getText();
        System.out.println("RFC ingresado: " + rfc); 

        Clientes cliente = Checar(rfc);

        if (cliente != null) {
            DefaultTableModel model = (DefaultTableModel) tblLicencia.getModel();
            model.setRowCount(0); 
            
            String discapacitado = "No";
            if(cliente.getDiscapacitado()){
                discapacitado = "Si";
            }
            
            Calendar fecha =  cliente.getFechaNacimiento();
            
            String nacimiento = fecha.get(fecha.YEAR)+"-"
                    +String.format("%02d", fecha.get(fecha.MONTH))+"-"
                    +String.format("%02d", fecha.get(fecha.DAY_OF_MONTH));
            
            Object[] rowData = {cliente.getId(), cliente.getNombreCompleto(), cliente.getTelefono(), nacimiento, discapacitado};
            model.addRow(rowData);
            btnContinuar.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado para el RFC ingresado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
    
    String rfc = jTextField1.getText();

    IConexion conexionBD = new ConexionBase(); 

    IClientesDAO clientesDAO = new ClientesDAO(conexionBD);

    Clientes cliente = clientesDAO.Checar(rfc);

    if (cliente != null) {
        try {
            // Cerrar la ventana actual
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            currentFrame.dispose();

            // Redirigir a la ventana FormTipoAutomovil
            FormTipoAutomovil formTipoAutomovil = new FormTipoAutomovil(cliente);
            formTipoAutomovil.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(SolicitarPlaca.this, "Error al abrir la ventana.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(SolicitarPlaca.this, "Cliente no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnRegresarActionPerformed
        FormInicio form = new FormInicio();
        form.setVisible(true);
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
    }//GEN-LAST:event_btnnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblLicencia;
    // End of variables declaration//GEN-END:variables

}