/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package com.mycompany.proyecto2_agenciafiscal;

import INegocios.ILicenciaNegocios;
import com.mycompany.proyecto2_agenciafiscaldominio.Clientes;
import com.mycompany.proyecto2_agencianegocio.LicenciaNegocio;
import com.mycompany.proyecto2_agenciapersistencias.ClientesDAO;
import com.mycompany.proyecto2_agenciapersistencias.ConexionBase;
import com.mycompany.proyecto2_agenciapersistencias.IClientesDAO;
import com.mycompany.proyecto2_agenciapersistencias.IConexion;
import com.mycompany.proyecto2_agenciapersistencias.ILicenciaDAO;
import com.mycompany.proyecto2_agenciapersistencias.LicenciaDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.Query;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oley
 */
public class SolicitarLicencia01 extends javax.swing.JPanel implements java.beans.Customizer {

    private Object bean;
    private int selectedRow = -1;
private ILicenciaDAO licenciaDAO;
    /**
     * Creates new customizer SolicitarLicencia01
     */
    public SolicitarLicencia01() {
          initComponents();

   
        
        
      
        
    }

    public void setObject(Object bean) {
        this.bean = bean;
    }

private Clientes Checar(String rfc) {
    System.out.println("Buscando cliente con RFC: " + rfc); 

    ConexionBase conexionBD = new ConexionBase();
    EntityManager entity = conexionBD.crearConexion();
    Query query = entity.createNativeQuery("SELECT * FROM Clientes WHERE rfc = ?", Clientes.class);
    query.setParameter(1, rfc);

    Clientes cli = null;
    try {
        cli = (Clientes) query.getSingleResult();
    } catch (NoResultException e) {
        cli = null;
    }

    if (cli != null) {
        System.out.println("Cliente encontrado: " + cli.toString());
    } else {
        System.out.println("Cliente no encontrado.");
    }

    return cli;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLicencia = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnAbrirLicencia = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("RFC:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 250, 20));

        tblLicencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Fecha de nacimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLicencia);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 540, 160));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        btnAbrirLicencia.setText("Continuar");
        btnAbrirLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirLicenciaActionPerformed(evt);
            }
        });
        add(btnAbrirLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String rfc = jTextField1.getText();
        System.out.println("RFC ingresado: " + rfc); 

        Clientes cliente = Checar(rfc);

        if (cliente != null) {
            DefaultTableModel model = (DefaultTableModel) tblLicencia.getModel();
            model.setRowCount(0); 
            Object[] rowData = { cliente.getNombreCompleto(), cliente.getTelefono(), cliente.getFechaNacimiento(),cliente.isDiscapacitado()};
            model.addRow(rowData);
        } else {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado para el RFC ingresado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormInicio formInicio = new FormInicio();
        formInicio.setVisible(true);
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAbrirLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirLicenciaActionPerformed
   String rfc = jTextField1.getText();

    // Aquí debes proporcionar una instancia válida de IConexion
    IConexion conexionBD = new ConexionBase(); // Esto es solo un ejemplo, reemplázalo con la instancia adecuada

    // Crear una instancia de ClientesDAO y pasar la conexión como argumento al constructor
    IClientesDAO clientesDAO = new ClientesDAO(conexionBD);

    // Llamar al método Checar en la instancia de ClientesDAO
    Clientes cliente = clientesDAO.Checar(rfc);

    if (cliente != null) {
        try {
            // Crear instancia de LicenciaDAO
            ILicenciaDAO licenciaDAO = new LicenciaDAO(conexionBD);

            // Crear instancia de LicenciaNegocio
ILicenciaNegocios licenciaNegocio = new LicenciaNegocio(licenciaDAO, clientesDAO, null);

            // Crear instancia de Licencia01 y pasar cliente y licenciaNegocio
            Licencia01 licenciaForm = new Licencia01(cliente, licenciaNegocio);

            // Crear JFrame y agregar el formulario Licencia01
            JFrame frame = new JFrame();
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.add(licenciaForm);
            frame.pack();
            frame.setVisible(true);

            // Cerrar el JFrame actual
            JFrame solicitarLicenciaFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            solicitarLicenciaFrame.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(SolicitarLicencia01.this, "Error al abrir la licencia.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(SolicitarLicencia01.this, "Cliente no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAbrirLicenciaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirLicencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblLicencia;
    // End of variables declaration//GEN-END:variables

}