/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Gui26
 */
public class FormReporte extends javax.swing.JFrame {

    /**
     * Creates new form FormSolicitarConsulta
     */
    public FormReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        btnNombre = new javax.swing.JRadioButton();
        btnTramite = new javax.swing.JRadioButton();
        btnPeriodo = new javax.swing.JRadioButton();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbTramite = new javax.swing.JComboBox<>();
        jDateFechaInicio = new com.toedter.calendar.JDateChooser();
        jDateFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnNombre.setText("Nombre");
        btnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombreActionPerformed(evt);
            }
        });

        btnTramite.setText("Tramite");
        btnTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramiteActionPerformed(evt);
            }
        });

        btnPeriodo.setText("Periodo");
        btnPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeriodoActionPerformed(evt);
            }
        });

        txtNombre.setEnabled(false);

        jLabel1.setText("Buscar por:");

        cbTramite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "licencia", "placa" }));
        cbTramite.setSelectedIndex(-1);
        cbTramite.setEnabled(false);
        cbTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTramiteActionPerformed(evt);
            }
        });

        jDateFechaInicio.setDateFormatString("yyyy-MM-dd");
        jDateFechaInicio.setEnabled(false);

        jDateFechaFin.setDateFormatString("yyyy-MM-dd");
        jDateFechaFin.setEnabled(false);

        jLabel2.setText("Fecha de inicio");

        jLabel3.setText("Fecha de fin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(btnContinuar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTramite)
                    .addComponent(btnNombre)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnPeriodo)
                            .addGap(15, 15, 15))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(cbTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTramite)
                    .addComponent(cbTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPeriodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnContinuar)))
                    .addComponent(jDateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FormInicio formInicio = new FormInicio();
        formInicio.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        String nombre=null;
        String tramiteString=null;
        Calendar fechaInicio=null;
        Calendar fechaFin=null;
        Boolean correcto = false;
        if (btnNombre.isSelected()){
            nombre=txtNombre.getText();
            correcto=true;
        }
        if (btnTramite.isSelected()){
            Object tramite = cbTramite.getSelectedItem();
            if (tramite!=null){
                tramiteString = tramite.toString();
                correcto=true;
            }else{
                correcto = false;
                JOptionPane.showMessageDialog(this, "No se eligio el tipo de tramite.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (btnPeriodo.isSelected()){
            fechaInicio = jDateFechaInicio.getCalendar();
            fechaFin = jDateFechaFin.getCalendar();
            if (fechaInicio!=null&&fechaFin!=null){
                correcto=true;
            }else{
                correcto = false;
                JOptionPane.showMessageDialog(this, "No se eligio una fecha", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }        
        if (correcto){
            FormTablaTramites form = new FormTablaTramites(nombre, tramiteString, fechaInicio, fechaFin);
            dispose();
            form.setVisible(true);
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramiteActionPerformed
        if (btnTramite.isSelected()){
            cbTramite.setEnabled(true);
        } else{
            cbTramite.setEnabled(false);
            cbTramite.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_btnTramiteActionPerformed

    private void cbTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTramiteActionPerformed
        
    }//GEN-LAST:event_cbTramiteActionPerformed

    private void btnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombreActionPerformed
        if (btnNombre.isSelected()){
            txtNombre.setEnabled(true);
        } else{
            txtNombre.setEnabled(false);
            txtNombre.setText("");
        }
    }//GEN-LAST:event_btnNombreActionPerformed

    private void btnPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeriodoActionPerformed
        if (btnPeriodo.isSelected()){
            jDateFechaInicio.setEnabled(true);
            jDateFechaFin.setEnabled(true);
        } else{
            jDateFechaInicio.setEnabled(false);
            jDateFechaFin.setEnabled(false);
            jDateFechaInicio.setCalendar(null);
            jDateFechaFin.setCalendar(null);
        }
    }//GEN-LAST:event_btnPeriodoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JRadioButton btnNombre;
    private javax.swing.JRadioButton btnPeriodo;
    private javax.swing.JRadioButton btnTramite;
    private javax.swing.JComboBox<String> cbTramite;
    private com.toedter.calendar.JDateChooser jDateFechaFin;
    private com.toedter.calendar.JDateChooser jDateFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
