/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package presentacion;

import INegocios.ILicenciaNegocios;
import dto.LicenciaNuevaDTO;
import entidades_JPA.Clientes;
import entidades_JPA.Licencia;
import negocio.LicenciaNegocio;
import daos.LicenciaDAO;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Oley
 */
public class Licencia01 extends javax.swing.JPanel implements java.beans.Customizer {

    private Clientes cliente;
    private ILicenciaNegocios LicenciaNegocio;
    private int anio = 0;
    private Object bean;

    /**
     * Creates new customizer Licencia
     */
public Licencia01(Clientes cliente, ILicenciaNegocios LicenciaNegocio) {
     this.cliente = cliente;
    this.LicenciaNegocio = LicenciaNegocio;
    initComponents(); // Aquí se inicializan todos los componentes, incluido Año
    precios(); 
}


    public void setObject(Object bean) {
        this.bean = bean;
        
    }

 public void precios() {
    if (Año.getSelectedItem().equals("1 año")) {
        if (cliente.getDiscapacitado()) { // Si el cliente está discapacitado
            txtcosto.setText("200");
        } else {
            txtcosto.setText("600");
        }
        anio = 1;
    } else if (Año.getSelectedItem().equals("2 año")) {
        if (cliente.getDiscapacitado()) { // Si el cliente está discapacitado
            txtcosto.setText("500");
        } else {
            txtcosto.setText("900");
        }
        anio = 2;
    } else if (Año.getSelectedItem().equals("3 año")) {
        if (cliente.getDiscapacitado()) { // Si el cliente está discapacitado
            txtcosto.setText("700");
        } else {
            txtcosto.setText("1100");
        }
        anio = 3;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Año = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtcosto = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Vigencia");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        Año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 año", "2 año", "3 año" }));
        Año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñoActionPerformed(evt);
            }
        });
        add(Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel2.setText("Costo:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        txtcosto.setEditable(false);
        txtcosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcostoActionPerformed(evt);
            }
        });
        add(txtcosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 100, -1));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 100, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel3.setText("Seleccione el tipo de licencia");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñoActionPerformed
        precios();
    }//GEN-LAST:event_AñoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        SolicitarLicencia01 solicitarLicencia01 = new SolicitarLicencia01();
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(solicitarLicencia01);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        JFrame frame2 = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame2.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
    agregar();

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtcostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostoActionPerformed


public void agregar() {
        float costo = Float.valueOf(txtcosto.getText());
        Calendar calendario = Calendar.getInstance();
        int ano = calendario.get(Calendar.YEAR) + anio;
        Calendar cal = new GregorianCalendar(ano, calendario.get(Calendar.MONTH), calendario.get(Calendar.DAY_OF_MONTH));
        Licencia licencia1 = new Licencia(anio, cal, costo, cliente);
        Licencia guardar = LicenciaNegocio.agregaLicencia(licencia1);
        
        if (guardar != null) {
            JOptionPane.showMessageDialog(this, "Se completo el tramite de licencia a nombre de: " + cliente.getNombreCompleto());
            FormInicio form = new FormInicio();
            form.setVisible(true);
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            frame.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Hubo un error al intentar completar su tramite");
        }
    }

   

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Año;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtcosto;
    // End of variables declaration//GEN-END:variables
}
